### ISSUE TITLE
La liste des dossiers / projets s'affichent à chaque fois que quelqu'un se connecte

### ISSUE THREAD

**Issue by sarahgarcin** [sarahgarcin/dodoc#10]

**Comment by sarahgarcin** [comment]
Refaire le système d'affichage des pages.

**Comment by sarahgarcin** [comment]
--> Essayer empty la div ??

**Comment by louis-ev** [comment]
première étape : faire un plan des events et de leurs fonctions
--> quel comportement, et pour quel résultat ?
