### ISSUE TITLE
CAPTURE : Ajout d'une alerte (pop-up) au changement de mode depuis le stop-motion.

### ISSUE THREAD

**Issue by paulinegourlet** [sarahgarcin/dodoc#104]
Oubli fréquent de validation du stop-motion et changement de mode efface le travail.
Si changement de mode sans validation : alerte ("Attention, vous devez valider votre stop-motion pour l'enregistrer. Si vous souhaitez le supprimer, cliquez sur la croix en haut à droite")

**Comment by sarahgarcin** [comment]
Que si nombre de frame > 1
