### ISSUE TITLE
éditeur de texte

### ISSUE THREAD

**Issue by paulinegourlet** [sarahgarcin/dodoc#115]

**Comment by paulinegourlet** [comment]
1/ ignore le formatage (saut de ligne etc) et si saut de ligne
2/ si pas de titre = prend la première ligne comme un titre

**Comment by louis-ev** [comment]
Utiliser parsedown pour parser le markdown ? https://github.com/hkdobrev/parsedown.js
L'idée étant que les retours à la ligne soient des <br>
