### ISSUE TITLE
réfléchir à comment envoyer les publi sur un ftp

### ISSUE THREAD

**Issue by sarahgarcin** [sarahgarcin/dodoc#128]

**Comment by louis-ev** [comment]
Un fichier HTML + sous-dossier "médias" ?

**Comment by philippejadin** [comment]
Je suis en train de tester cet outil. Concernant la publication, ce qui serait vraiment super, c'est de pouvoir simplement uploader toutes les données (par ftp ou rsync) sur un serveur statique, et d'avoir un "player" statique lui aussi, qui récupèrerait et afficherait toutes les infos à l'aide de javascript côté client uniquement. 

De cette manière, le contenu pourrait être hébergé sur un bête serveur (style ovh) et ce serveur contiendrait automatiquement un backup de toutes les données.
Est-ce faisable?
