### ISSUE TITLE
pb avec le format webm : on ne peux pas utiliser la barre de navigation dans la vidéo

### ISSUE THREAD

**Issue by paulinegourlet** [sarahgarcin/dodoc#132]
Quand on veut se balader dans la vidéo on ne peut pas, on est obligé de la regarder en entier, linéairement. Le player ne marche pas.

**Comment by louis-ev** [comment]
Est-ce que tu peux tester le lien suivant dans le même navigateur et confirmer que tu arrives bien à te déplacer dans cette vidéo là ? 
http://techslides.com/demos/sample-videos/small.webm

**Comment by paulinegourlet** [comment]
oui là ça marche...
p.

2016-03-25 19:30 GMT+01:00 Louis Eveillard <notifications@github.com>:
