### ISSUE TITLE
Interface de capture choix camera

### ISSUE THREAD

**Issue by sarahgarcin** [sarahgarcin/dodoc#137]
Ajouter un champ de selection de la camera (lister toutes les cameras disponibles)
Exemple: https://webrtc.github.io/samples/src/content/devices/input-output/

**Comment by sarahgarcin** [comment]
Retour d'Anthony - bug
Sous Dodoc, sais tu comment desactiver la webcam d'un portable? Car pour capturer une video, je vois bien le flux de ma webcam mobile sous dodoc, mais ensuite, la video me sort le flux de la webcam du portable ....

**Comment by louis-ev** [comment]
Bingouse !
Faudrait demander à Anthony si c'est bon maintenant.
