### ISSUE TITLE
Page capture - temps de latence entre les prises de vue du stop motion

### ISSUE THREAD

**Issue by sarahgarcin** [sarahgarcin/dodoc#141]
On ne peut plus prendre plein de photos à la suite dans le stop motion, il faut attendre une demi secondes avant de prendre la photo suivante. Je trouve que c'est un peu dommage.

**Comment by louis-ev** [comment]
What ? Mais il me semblait que c'était ce qu'on voulait, ajouter un delay pour éviter la prise de pleins de médias d'affilés !
Du coup je réduis à 0.4s, mieux ?

**Comment by paulinegourlet** [comment]
yes :)
