### ISSUE TITLE
Page capture - 13 pouces bouton capture coupé

### ISSUE THREAD

**Issue by sarahgarcin** [sarahgarcin/dodoc#142]
Le bouton capture est toujours coupé en bas de mon écran.

**Comment by louis-ev** [comment]
Nouvelle version ! La taille de la preview est en max-width moitié de l'écran, avec une hauteur en vh (donc en théorie ça rentre presque toujours complètement).

**Comment by louis-ev** [comment]
La navbar est aussi plus petite de 10px

**Comment by louis-ev** [comment]
C'est encore le cas ?
