### ISSUE TITLE
Problème avec le média SON dans PUBLI et CAPTURE

### ISSUE THREAD

**Issue by paulinegourlet** [sarahgarcin/dodoc#189]
Problème avec la barre de lecture /
- dans publi : dans tous les templates (sauf une colonne) > son est une image, pas de lecteur
- dans capture : lecteur ne s'affiche pas correctement, il n'y a qu'un bouton play. (avant, barre de lecture et on pouvait se balader dedans)

![image](https://cloud.githubusercontent.com/assets/7995654/20298235/fece3c08-ab14-11e6-9f5e-1667523ae4f7.png)

**Comment by louis-ev** [comment]
fixed https://github.com/sarahgarcin/dodoc/commit/ac151fb15ff6f4a4c002f1aac1c7f4e1aa5f7836
