### ISSUE TITLE
stockage des contenus et médias

### ISSUE THREAD

**Issue by louis-ev** [sarahgarcin/dodoc#192]
Suite au passage sur electron et à la diffusion prochaine au plus grand nombre, il me paraît important de repenser l’organisation du dossier `sessions` (pourquoi s'appelle t'il sessions au fait ?).

Je pense qu'il y a 3 dossiers qui mériteraient d'être accessibles au plus grand nombre pour permettre l'export, la modification ou la suppression de contenus sans passer par l'interface : 

1. sessions (que je vous propose de renommer en _contenus_, mais peut-être faut-il trouver un nom qui marche aussi en anglais ? en tout cas _sessions_ c'est pas suffisamment clair je pense) 

2. publications (qui récupère les publications exportées, faut-il l'appeler _publications-exportees_ ou bien _publications_ suffit comme nom ? au moins mettre un petit readme qui dit que ce dossier ne contient que les publis préalablement exportées)

3. templates (ou _gabarits-de-publication_ ?)

Concernant l'emplacement de stockage de ces contenus, je vous propose les choses suivante :

- pour la version node.js de dodoc, continuer à stocker les contenus dans le dossier principal pour que les utilisateurs (probablement plus expert que les autres) aient tout au même endroit.

- pour les utilisateurs d'electron, demander au premier lancement l'emplacement de stockage avec un filepicker. Un bouton dans l'interface permettrait de modifier cela plus tard.

Avantages : s'adapte à tous les OS et type d'utilisations
Inconvénients : si la première personne à l'utiliser navigue depuis un autre appareil ? Si le dossier n'est pas disponible au lancement car il a été déplacé ou mis sur une clé ? et aussi, plus compliqué à implémenter

--> pour aller vite, je vous propose d'utiliser le dossier "documents" tel que décrit dans la [doc d'electron](http://electron.atom.io/docs/all/#appgetpathname) : `documents Directory for a user’s “My Documents”.`. Si la demande est faite plus tard par d'autres utilisateurs nous pourrions proposer de modifier ce choix par défaut.
Cela veut dire qu'il faut constituer cette structure de dossier si elle n'existe pas par défaut. Peut-être imaginer une structure de dossier vide avec qq readme si besoin (pour chaque dossier principal : _contenus_, _templates_ et _publications_. L'idée serait de permettre aux utilisateurs de se partager des contenus, des templates et des publications juste en passant par un copié collé et pas par nous.
Ces 3 dossiers seraient réunis dans un dossier nommé "dodoc" pour plus de clarté. Dans la version node.js ce dossier 

Voici des captures d'écran de structure de dossiers/fichiers simulant ce que j'évoque pour que vous voyiez mieux ce que je propose : 

(il manque le dossier _dodoc/publications_ dans les 2 premières captures ci-dessous)
![dodoc-chemin-projets](https://cloud.githubusercontent.com/assets/1948417/20311797/62382542-ab51-11e6-9185-3b4fc020166e.png)

![dodoc-chemin-templates](https://cloud.githubusercontent.com/assets/1948417/20311800/6609d08a-ab51-11e6-99c7-734ec5b2149b.png)

![dodoc-chemin-publications](https://cloud.githubusercontent.com/assets/1948417/20311805/67e50b2c-ab51-11e6-9289-66ecb7bf1040.png)

Votre avis ?

**Comment by louis-ev** [comment]
Bingo ? Vous validez ?

**Comment by paulinegourlet** [comment]
Coucou,
comme je te le disais hier soir, c'est bon pour moi avec en tête le
challenge graphique de bien situer l'info pour que les gens sachent où
aller chercher leurs fichiers.

On se ping-pong dans la journée sur le reste. J'ai un prb pour tester.

Bisous !

2016-11-16 9:34 GMT+01:00 Louis Eveillard <notifications@github.com>:

**Comment by louis-ev** [comment]
Done.
Une partie de la logique (celle qui duplique le dossier /user et le place ailleurs) est dans dodoc-app : https://github.com/l-atelier-des-chercheurs/dodoc-app/blob/master/main.js
