### ISSUE TITLE
Rapport Bugs PAGE 1 — 18.01.2016

### ISSUE THREAD

**Issue by paulinegourlet** [sarahgarcin/dodoc#2]
- quand création de plusieurs dossier à la suite - bug systématique : 3 pages d'alerte 'nom déjà pris' (mais crée le dossier en fait quand même) 
- à la suppression : besoin de recharger la page
- quand on choisit le statut > terminé : 
1/demande de validation = manque boutons 'OK' ou 'annuler'.
2/quand on valide = 'ce nom est déjà pris'

**Comment by sarahgarcin** [comment]
Ok ! J'avais noté les mêmes bugs de mon côté. 
J'avance dans la semaine.

**Comment by sarahgarcin** [comment]
Done !
