### ISSUE TITLE
afficher le logo et les boutons (retour et plus) dans une barre fixed en haut

### ISSUE THREAD

**Issue by paulinegourlet** [sarahgarcin/dodoc#22]
cf. mock up (avec petite anim comme tu sais si bien les faire Louis!)

**Comment by louis-ev** [comment]
I'm on it.
Mais je suis vraiment pas convaincu par les boutons dans la navbar. pourquoi pas cliquer sur les noms éléments directement (et donc en faire des boutons bien affordants) ? 
D'autre part on sent pas bien si c'est un indicateur de la position où on se trouve, ou un menu de navigation. Ça peut être les deux mais il faut sentir la différence. Je fais des tests

**Comment by paulinegourlet** [comment]
Je suis ouverte à des hacks de mes mockups si tu as des idées précises
d'amélioration. No souci, t'as compris l'idée: l'enfant doit 1/bien
comprendre l'idée de chemin et 2/ comprendre comment naviguer. Pour
l'instant nous n'avons aucune donnée terrain car c'est tjs moi qui navigue,
les gamins sont paumés...
Le 9 févr. 2016 15:38, "Louis Eveillard" <notifications@github.com> a
écrit :

**Comment by louis-ev** [comment]
Une proposition rapide : transformer les boutons en "bouton-texte", pour clarifier les effets et la nomenclature.
Plutôt qu'une flèche arrière, j'ai mis des petits rectangles qui rappellent la 

![image](https://cloud.githubusercontent.com/assets/1948417/12920548/566f9e82-cf49-11e5-9188-d30648bdeec5.png)

Dans la page d'un projet, on pourrait garder la page en cours (bibliothèque ou capture, ou publication) + les options de navigation. Mais c'est pas encore très clair la page où on se trouve.
Dans la vignette en dessous, on est sur la page bibliothèque ou capture ?

![image](https://cloud.githubusercontent.com/assets/1948417/12920972/5476ad62-cf4b-11e5-975a-2d0eb965ad70.png)

On pourrait avoir deux styles différents : anguleux et pleine hauteur pour le fil d'ariane, et en forme de bouton pour les autres pages, les options.
Je test rapidement

**Comment by louis-ev** [comment]
Ça donnerait ça : 

![image](https://cloud.githubusercontent.com/assets/1948417/12921153/17ddbc6e-cf4c-11e5-89b5-67084e612c09.png)

Vous en pensez quoi ?
