### ISSUE TITLE
problème affichage textes

### ISSUE THREAD

**Issue by paulinegourlet** [sarahgarcin/dodoc#54]
- fer à gauche au lieu de à droite
- quand beaucoup de texte, mettre un scroll ou un hidden...
- bug > j'ai mis bcp de texte et une ligne dépasse sur le texte d'à côté 
- ils ne doivent pas rester alignés en haut mais ce mettre par date de création, mélangés avec les autres médias
- interlignage du titre et typo titre trop gros

**Comment by sarahgarcin** [comment]
Fixed -> ils ne doivent pas rester alignés en haut mais ce mettre par date de création, mélangés avec les autres médias
