### ISSUE TITLE
BIBLI : mettre un highlight sur les vignettes

### ISSUE THREAD

**Issue by louis-ev** [sarahgarcin/dodoc#77]
deux manière de highlight : 
1. au survol sur les vignettes une icone apparait et peut être cliqué
2. dans le plein écran d'un média possibilité de toggle le highlight

**Comment by louis-ev** [comment]
mettre une classe "is--highlight" pour les médias highlighté

**Comment by louis-ev** [comment]
L'icône qui apparait sur une vignette pour la "highlighter" peut être un petit drapeau en haut à droite, par exemple.

**Comment by sarahgarcin** [comment]
Faire un toogle aussi dans l'édition du média
