### ISSUE TITLE
Page projet: le titre de la publi est le titre du projet (mais est corrigé après rafraîchissement)

### ISSUE THREAD

**Issue by sarahgarcin** [sarahgarcin/dodoc#87]

**Comment by louis-ev** [comment]
lapin compris

**Comment by louis-ev** [comment]
Pour reproduire : ouvrir une publi, éditer son titre, le sauvegarder, puis retourner à la liste des publis.
La publi dont le titre a changé aura encore son ancien titre.

Pour solutionner
- quand node a enregistré un nouveau titre, il déclenche un événement `lister les publications`
- le .js de la page récupère cet événement et re-liste toutes les publis
