### ISSUE TITLE
BIBLI: manque d'affordance et d'ergo sur le drag an drop

### ISSUE THREAD

**Issue by sarahgarcin** [sarahgarcin/dodoc#90]
drag and drop à la suite super dur car bout de 'blanc' disponible sous la dernière image de la publi trop petit. Le bloc gris qui apparaît et qui 'afforde' que tu peux lâcher n'est pas assez visible. Du coup, la personne lâche mais dans le vent et ça marche pas.
Donc je dirai : couleur genre jaune pour signifier un nouvel emplacement possible et plus de blanc sous la dernière image pour laisser la place d'insérer à la suite

**Comment by louis-ev** [comment]
- les encarts sont plus grands, plus visibles
- maintenant, en glissant un media vers le bord haut ou bas d'une publi, elle scroll. Pratique pour se déplacer dans la publi.

**Comment by paulinegourlet** [comment]
- Je trouve ça encore un peu faible niveau affordance. (vidéo à l'appui où le mec lâche sans chercher à voir si il y a ou pas un encart qui lui signale un nouvel emplacement) je pense qu'une couleur (gris coloré?) serait bienvenue.
- Le scroll est bien, est-ce possible de le faire aller un peu plus vite ?

**Comment by louis-ev** [comment]
C'est fait, tu peux test ?
